language: python
python:
  - "2.7"

install:
  - sudo apt-get iverilog
  - sudo apt-get libopenblas-base
  - pip install -r requirements.txt --use-mirrors

env:
  global:
    - COCOTB=`pwd`/cocotb
  matrix:
    - TESTFOLDER=tests
    - TESTFOLDER=tests/units

script: "nosetests $TESTFOLDER"
