language: python
python:
  - "2.7"

cache: apt

install:
  - sudo apt-get update -qq
  - sudo apt-get install iverilog
  - sudo apt-get install libopenblas-base
  - pip install -r requirements.txt --use-mirrors

env:
  global:
    - COCOTB=`pwd`/cocotb
  matrix:
    - TESTFOLDER=tests
    - TESTFOLDER=tests/units

script: "nosetests $TESTFOLDER"
